id: P004156
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 10:57:04.449358
source_metadata:
  id: bdr:W00EGS1017357
  title: གསུང་འབུམ། བློ་བཟང་རབ་གསལ
  author: ''
  volumes:
    703ff12cdbfc402c8dff1de488161e43:
      image_group_id: I00KG08390
      title: ''
      volume_number: 1
      total_pages: 824
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
