id: P004156
initial_creation_type: ocr
source_metadata:
  id: bdr:W00EGS1017357
  title: གསུང་འབུམ། བློ་བཟང་རབ་གསལ
  author: ''
  volumes:
    703ff12cdbfc402c8dff1de488161e43:
      image_group_id: I00KG08390
      title: ''
      volume_number: 1
      total_pages: 824
