id: I7F3F5E9D
legacy_id: P004156
ocr_import_info:
  bdrc_scan_id: W00EGS1017357
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T07:22:30'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-29T11:08:57.568493+00:00'
last_modified: 2022-08-29 19:10:26.197113
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W00EGS1017357
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW00EGS1017357
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། བློ་བཟང་རབ་གསལ།
  author: དཔའ་རིས་རབ་གསལ།
statistics:
  ocr_word_mean_confidence_index: 0.9401402111104178
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I00KG08390:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG08390
      total_pages: 824
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I00KG08390.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9401402111104178
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
